// import Head from 'next/head';
// import Image from 'next/image';
// import { Inter } from '@next/font/google';
// import styles from '@/styles/Home.module.css';

// const inter = Inter({ subsets: ['latin'] });

// export default function Home() {
//   return (
//     <>
//       <Head>
//         <title>Create Next App</title>
//         <meta name='description' content='Generated by create next app' />
//         <meta name='viewport' content='width=device-width, initial-scale=1' />
//         <link rel='icon' href='/favicon.ico' />
//       </Head>
//       {/* <main className={styles.main}>
//         <div className={styles.description}>
//           <p>
//             Get started by editing&nbsp;
//             <code className={styles.code}>src/pages/index.js</code>
//           </p>
//           <div>
//             <a
//               href='https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app'
//               target='_blank'
//               rel='noopener noreferrer'
//             >
//               By{' '}
//               <Image
//                 src='/vercel.svg'
//                 alt='Vercel Logo'
//                 className={styles.vercelLogo}
//                 width={100}
//                 height={24}
//                 priority
//               />
//             </a>
//           </div>
//         </div>

//         <div className={styles.center}>
//           <Image
//             className={styles.logo}
//             src='/next.svg'
//             alt='Next.js Logo'
//             width={180}
//             height={37}
//             priority
//           />
//           <div className={styles.thirteen}>
//             <Image
//               src='/thirteen.svg'
//               alt='13'
//               width={40}
//               height={31}
//               priority
//             />
//           </div>
//         </div>

//         <div className={styles.grid}>
//           <a
//             href='https://nextjs.org/docs?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app'
//             className={styles.card}
//             target='_blank'
//             rel='noopener noreferrer'
//           >
//             <h2 className={inter.className}>
//               Docs <span>-&gt;</span>
//             </h2>
//             <p className={inter.className}>
//               Find in-depth information about Next.js features and&nbsp;API.
//             </p>
//           </a>

//           <a
//             href='https://nextjs.org/learn?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app'
//             className={styles.card}
//             target='_blank'
//             rel='noopener noreferrer'
//           >
//             <h2 className={inter.className}>
//               Learn <span>-&gt;</span>
//             </h2>
//             <p className={inter.className}>
//               Learn about Next.js in an interactive course with&nbsp;quizzes!
//             </p>
//           </a>

//           <a
//             href='https://vercel.com/templates?framework=next.js&utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app'
//             className={styles.card}
//             target='_blank'
//             rel='noopener noreferrer'
//           >
//             <h2 className={inter.className}>
//               Templates <span>-&gt;</span>
//             </h2>
//             <p className={inter.className}>
//               Discover and deploy boilerplate example Next.js&nbsp;projects.
//             </p>
//           </a>

//           <a
//             href='https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app'
//             className={styles.card}
//             target='_blank'
//             rel='noopener noreferrer'
//           >
//             <h2 className={inter.className}>
//               Deploy <span>-&gt;</span>
//             </h2>
//             <p className={inter.className}>
//               Instantly deploy your Next.js site to a shareable URL
//               with&nbsp;Vercel.
//             </p>
//           </a>
//         </div>
//       </main> */}
//     </>
//   );
// }

import React, { useState } from 'react';
import Image from 'next/image';
import {
  Button,
  Container,
  Icon,
  Menu,
  Segment,
  Sidebar,
  Visibility,
  Grid,
} from 'semantic-ui-react';

import HomepageHeading from '../components/HomepageHeading';
import HomepageLayout from '../components/HomepageLayout';

export default function ResponsiveContainer() {
  const [isFixedMenuShow, setShowFixedMenu] = useState(false);
  const [isSidebarOpened, setSidebarOpened] = useState(false);

  return (
    <Grid columns={1}>
      <Grid.Column only='computer'>
        <Visibility
          once={false}
          onBottomPassed={() => setShowFixedMenu(true)}
          onBottomPassedReverse={() => setShowFixedMenu(false)}
        >
          <Segment
            inverted
            textAlign='center'
            style={{ minHeight: 700, padding: '1em 0em', background: 'none' }}
            vertical
          >
            <Image
              src='/images/title-fireplace.webp'
              alt='грузинская печь'
              fill
              style={{ objectFit: 'cover', zIndex: -1 }}
            />
            <Menu
              fixed={isFixedMenuShow ? 'top' : null}
              inverted={!isFixedMenuShow}
              pointing={!isFixedMenuShow}
              secondary={!isFixedMenuShow}
              size='large'
            >
              <Container>
                <Menu.Item as='a' active>
                  Home
                </Menu.Item>
                <Menu.Item as='a'>Work</Menu.Item>
                <Menu.Item as='a'>Company</Menu.Item>
                <Menu.Item as='a'>Careers</Menu.Item>
                <Menu.Item position='right'>
                  <Button as='a' inverted={!isFixedMenuShow}>
                    Log in
                  </Button>
                  <Button
                    as='a'
                    inverted={!isFixedMenuShow}
                    primary={isFixedMenuShow}
                    style={{ marginLeft: '0.5em' }}
                  >
                    Sign Up
                  </Button>
                </Menu.Item>
              </Container>
            </Menu>
            <HomepageHeading />
          </Segment>
        </Visibility>
        <HomepageLayout />
      </Grid.Column>
      <Grid.Column only='tablet mobile'>
        <Sidebar.Pushable>
          <Sidebar
            as={Menu}
            animation='overlay'
            inverted
            onHide={() => setSidebarOpened(false)}
            vertical
            visible={isSidebarOpened}
          >
            <Menu.Item as='a' active>
              Home
            </Menu.Item>
            <Menu.Item as='a'>Work</Menu.Item>
            <Menu.Item as='a'>Company</Menu.Item>
            <Menu.Item as='a'>Careers</Menu.Item>
            <Menu.Item as='a'>Log in</Menu.Item>
            <Menu.Item as='a'>Sign Up</Menu.Item>
          </Sidebar>

          <Sidebar.Pusher dimmed={isSidebarOpened}>
            <Segment
              inverted
              textAlign='center'
              style={{ minHeight: 350, padding: '1em 0em', background: 'none' }}
              vertical
            >
              <Image
                src='/images/title-fireplace.webp'
                alt='грузинская печь'
                fill
                style={{ objectFit: 'cover', zIndex: -1 }}
              />
              <Container>
                <Menu inverted pointing secondary size='large'>
                  <Menu.Item
                    onClick={() => setSidebarOpened((prevState) => !prevState)}
                  >
                    <Icon name='sidebar' />
                  </Menu.Item>
                  <Menu.Item position='right'>
                    <Button as='a' inverted>
                      Log in
                    </Button>
                    <Button as='a' inverted style={{ marginLeft: '0.5em' }}>
                      Sign Up
                    </Button>
                  </Menu.Item>
                </Menu>
              </Container>
              <HomepageHeading />
            </Segment>

            <HomepageLayout />
          </Sidebar.Pusher>
        </Sidebar.Pushable>
      </Grid.Column>
    </Grid>
  );
}
